FROM mcr.microsoft.com/dotnet/sdk:8.0
ENV TZ=Asia/Tokyo
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
# src 配下をすべてコピー
COPY src/ ./src/
EXPOSE 3000
# 依存関係を復元
RUN dotnet restore src/Smart.Api/Smart.Api.csproj
CMD ["dotnet", "watch", "--project", "src/Smart.Api/Smart.Api.csproj", "--urls", "http://0.0.0.0:3000"]