/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/BackButton.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CardList: typeof import('./components/CardList.vue')['default']
    ContentWrapper: typeof import('./components/ContentWrapper.vue')['default']
    DetaiCard: typeof import('./components/DetaiCard.vue')['default']
    DetailCard: typeof import('./components/DetailCard.vue')['default']
    DetailCardList: typeof import('./components/DetailCardList.vue')['default']
    Fixed: typeof import('./components/Fixed.vue')['default']
    FixedScrollLayout: typeof import('./components/FixedScrollLayout.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterButton: typeof import('./components/FooterButton.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Info: typeof import('./components/Info.vue')['default']
    InfoIcon: typeof import('./components/InfoIcon.vue')['default']
    InfoMessage: typeof import('./components/InfoMessage.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    LinkButton: typeof import('./components/LinkButton.vue')['default']
    MeasureButton: typeof import('./components/MeasureButton.vue')['default']
    MeasureWeightButton: typeof import('./components/MeasureWeightButton.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ReMeasure: typeof import('./components/ReMeasure.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VolumeLongestSideSettingsModal: typeof import('./components/VolumeLongestSideSettingsModal.vue')['default']
    VolumeWeightSettingsModal: typeof import('./components/VolumeWeightSettingsModal.vue')['default']
  }
}
